application: fpmi2013
version: master
runtime: python20
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /(.*\.html)
  mime_type: text/html
  static_files: /\1
  upload: static/(.*\.html)

- url: /
  static_files: /\1
  upload: /
