handlers:
- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /view
  static_dir: static/view

- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: (.*)

